### PR TITLE
Fix https usage and invalid json for batches

### PR DESCRIPTION
**Pull request by Mairu**
* https was is not working for me without that change
* we have a scenario with nginx with mod security in front of seq which refuses to pass through the request because of the invalid json body

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks! Surprising that the JSON bug has been lurking there for _six years_!

The test failures are due to some flakiness we're yet to flush out when running in GitHub actions - the change looks good to me :+1:

**Comment by nblumhardt** [comment]
The `http` vs `https` change is interesting - I've checked the documentation for `request` and the `options` it supports do include `protocol`:

https://nodejs.org/api/http.html#http_http_request_options_callback

Wonder whether we need to dig into this further?

**Comment by Mairu** [comment]
Thank you for that fast response.

For the protocol, the "problem" is, that you provide your own agent, and then the protocol of the agent and the request does not match. It seems that the agent ones is used in such cases.

**Comment by nblumhardt** [comment]
Thanks for the follow-up. We tested this out locally, and got a hard failure early on in the sending of the request (protocol not supported), so it doesn't appear that any HTTP request was being sent in the earlier/broken version. New build should have this all sorted out now :-) .. Thanks again!

**Pull request merged**
